# Generated by Django 5.0.7 on 2024-08-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='media/user_dp/user.jpeg', upload_to='media/user_dp/'),
        ),
    ]
